### ISSUE TITLE
JUnit reporter

### ISSUE THREAD

**Issue by zewa666** [spekt/xunit.testlogger#13]
Hi there, great work you did here. Sadly quite a lot of tools prefer JUnit reports instead of XUnits, so I'd like to ask if you know about any JUnit capable testlogger?

**Comment by codito** [comment]
@zewa666 sorry, I am not aware of a junit testlogger. Here's a workaround that may help: https://github.com/spekt/nunit.testlogger/issues/47#issuecomment-462604045

**Comment by zewa666** [comment]
Thanks for the hint @codito. I'll take a look there.
