### ISSUE TITLE
Skipping reason for test should be included in output file

### ISSUE THREAD

**Issue by Jazzman82** [spekt/xunit.testlogger#16]
When a test is skipped with setting the Skip-Property in the [Fact]-Attribute, you can set a string with additional information, e.g. why the test is skipped: e.g. `[Fact(Skip = "Reason")]`
In VisualStudio, this message is displayed in the output of the test and when using the xunit.console.runner with the -xml switch, it is also included like specified here: [xUnit.net v2 XML Format](https://xunit.github.io/docs/format-xml-v2.html).

I've played around a little bit to achieve this behaviour and can make a PR for this.

**Comment by codito** [comment]
Fixed with 734876d
