### ISSUE TITLE
Documentation misleading

### ISSUE THREAD

**Issue by tomeks666** [spekt/xunit.testlogger#20]
This did not work:
> dotnet test --test-adapter-path:. --logger:xunit

This did work:
> dotnet test  --logger:xunit

dotnet 2.1 project

**Comment by codito** [comment]
Which version of `dotnet sdk` are you using?

**Comment by tomeks666** [comment]
The project is targeted on 2.1, but in the log I see something like that:

c:\temp\workspace\xxxxxxxxxx_master>dotnet test  --logger  "xunit" 
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(187,5): warning NETSDK1071: A PackageReference to 'Microsoft.AspNetCore.App' specified a Version of `2.1.3`. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs [c:\temp\workspace\xxxxxxxxxx_master\src\Web\Web.csproj]

So while there is number od SDKs installed from 2.1.700 - 3.0.100 it seems to pickup 3.0.100. If I am interpreting this correctly.
