### ISSUE TITLE
Dotnet test  Solution file does not create a result per test project

### ISSUE THREAD

**Issue by mubeda** [spekt/xunit.testlogger#21]
Basically the problem happens when a solution has more the one Xunit test project. So if you execute "dotnet test" for the solution TestResult.xml is always overwrite by the last executed unit test project. May be a solution could be to create a time stamp based file name if LogFilePath is not specified.

**Comment by Siphonophora** [comment]
@mubeda Could you share the full command line arguments you are using?

**Comment by mubeda** [comment]
Sure!
dotnet test --logger xunit --configuration Debug --results-directory X:\test02\ --no-build. At on the directory where the solution file is located.

**Comment by Siphonophora** [comment]
@mubeda Thanks. This logger doesn't have an option to modify the file name per project, like some of our other loggers. We are working on making these features consistent across the loggers, but it will still be a little while before thats done. 

For now, I would suggest running with the folder as an argument, so you run one command per project and can name them separately.  
`dotnet test .\ProjectOne --logger:"xunit;LogFilePath=ProjectOne_test_result.xml"`

**Comment by mubeda** [comment]
Tks!! 
For the moment i cloned the repo, and did little changes to create files using the combination of FileName+TIMESTAMP.   That solved my problem for the moment, until you can work on them. Tks!

**Comment by jdelucaa** [comment]
This one would be a great addition :)

**Comment by codito** [comment]
Supported with `{assembly}` and `{framework}` token in options in [3.0.56][] release. Documentation for this feature is at https://github.com/spekt/testlogger/wiki/Logger-Configuration

[3.0.56]: https://www.nuget.org/packages/XunitXml.TestLogger/3.0.56
