### ISSUE TITLE
Wrong test name when using custom framework

### ISSUE THREAD

**Issue by D0tNet4Fun** [spekt/xunit.testlogger#57]
Hello,

I found an issue with the Xunit logger when using it with my Xunit-based custom test framework. Let me give you a bit of context: 

> This test framework allows using a class to define a test case. For example this is a test case having 6 steps:
>```csharp
> [TestCase("TC0001")]
> public class DemoTestCase
> {
>     [Summary("Login to web site")] public void LoginToWebsite() { }
>
>     [Precondition(1, "The web site must be deployed on the web server")] private void DeployWebSite() { }     
>     [Precondition(2, "The web site must be accessible via HTTPS")] private void EnableHttps() { }
>     [Input(1, "Access the web site")] private void AccessWebSite() { }
>     [Input(2, "Enter user name and password")] private void EnterUserNameAndPassword() { }
>     [Input(3, "Click the login button")] private void Login() { }
>     [ExpectedResult(3, "The user should be logged in")] private void VerifyUserIsLoggedIn() { }
> }
> ```
> In the discovery phase this shows up as a single test case named "Login to web  site". When run, this test case produces 7 results: one for each of the 6 steps and another one for the Summary. Here's what this looks like in the VS Test Explorer:
> 
> <img src="https://github.com/spekt/xunit.testlogger/assets/17428504/1ad2b35b-45bc-4dfb-a71d-75ac88906f22" width="512" />

The issue I found is that the test report contains the `7` test results as expected, but they all have the same name "Login to web site":
```xml
<test name="Login to web site" type="Automation.TestFramework.Tests.DemoTestCase" method="LoginToWebsite" time="0.0009059" result="Pass">
  <traits />
</test>
```
By contrast, the `trx` test report contains the correct names as provided by my framework:
```xml
<Results>
  <UnitTestResult testName="[1/6] [Precondition] 1. The web site must be deployed on the web server" />
  <UnitTestResult testName="[3/6] [Input] 1. Access the web site" />
  <UnitTestResult testName="[4/6] [Input] 2. Enter user name and password" />
  <UnitTestResult testName="[5/6] [Input] 3. Click the login button" />
  <UnitTestResult testName="Login to web site" />
  <UnitTestResult testName="[6/6] [Expected result] 3. The user should be logged in" />
  <UnitTestResult testName="[2/6] [Precondition] 2. The web site must be accessible via HTTPS" />
</Results>
<TestDefinitions>
  <UnitTest name="Login to web site" storage="d:\work\automation.testframework.git\automation.testframework.tests\bin\debug\net8.0\automation.testframework.tests.dll">
    <Execution id="b69d9c91-53d7-4d4c-bbd3-688099c61c1f" />
    <TestMethod codeBase="d:\Work\Automation.TestFramework.git\Automation.TestFramework.Tests\bin\Debug\net8.0\Automation.TestFramework.Tests.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Automation.TestFramework.Tests.DemoTestCase" name="LoginToWebsite" />
  </UnitTest>
</TestDefinitions>
```
The `trx` logger makes this difference between the test case name and the test result name, whereas the `xunit` logger does not. 

Could you update the logger to use the test result name in this case, please?

**Comment by D0tNet4Fun** [comment]
I've done some digging and found out that the data I need is available on the `TestResultInfo`, although they are internal properties:
```csharp
XunitXmlSerializer.CreateTestElement(TestResultInfo result)

result.TestCaseDisplayName = "Login to web site"
result.TestResultDisplayName = "[1/6] [Precondition] 1. The web site must be deployed on the web server"
```

**Comment by codito** [comment]
@D0tNet4Fun thanks for reporting this. Capturing the ask in https://github.com/spekt/testlogger/issues/85, hope making the test name configurable will be a generic approach and help custom frameworks.

**Comment by D0tNet4Fun** [comment]
@codito thank you for getting back to me. Since then I made other changes to resolve this issue, this time in the `testlogger` repo. I am happy with the results, but I can't evaluate the impact on other frameworks. However, I created this [draft PR](https://github.com/D0tNet4Fun/testlogger/pull/3) that I'd like to ask you to review.

**Comment by codito** [comment]
@D0tNet4Fun thank you for sharing an update. The changes will impact only xunit like frameworks.

**Comment by codito** [comment]
Closing this issue since the fix is externally implemented.
