### ISSUE TITLE
Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'xunit'.

### ISSUE THREAD

**Issue by sd185190** [spekt/xunit.testlogger#58]
When using XunitXml.TestLogger, I am getting error like below when running the test projects from the solution level.
The command I used is: dotnet test --logger:"xunit;LogFilePath=test_result.xml" --no-build -c "Release"
The error is: Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'xunit'.

I added the package as a reference in packages.config file like below.
**<package id="XunitXml.TestLogger" version="3.1.20" targetFramework="net472" />**

Could you please help us how can I resolve this?

**Comment by codito** [comment]
@sd185190 need more info to diagnose. Please see https://github.com/spekt/testlogger/wiki/Troubleshooting. If possible share a repro project and reopen the issue.
