### ISSUE TITLE
Incorrect time format fails XUnitBuilder

### ISSUE THREAD

**Issue by jayeshu** [spekt/xunit.testlogger#6]
TestLogger generates following XML tag. Notice the time has comma in it.
< assembly run-date="2018-09-05" run-time="17:42:10" total="506" passed="506" failed="0" skipped="0" time="1,244.415" errors="0" >

Once this file is given to XUnitBuilder in Jenkins , it reports following : 
org.jenkinsci.plugins.xunit.service.TransformerException: Conversion error: Cannot convert string "1.244.415" to a double
	at org.jenkinsci.plugins.xunit.service.XUnitConversionService.convert(XUnitConversionService.java:81)
	at org.jenkinsci.plugins.xunit.service.XUnitTransformerCallable.invoke(XUnitTransformerCallable.java:120)
	at org.jenkinsci.plugins.xunit.service.XUnitTransformerCallable.invoke(XUnitTransformerCallable.java:39)

Recommended solution is to avoid comma in generated time value.

**Comment by Jensaarai** [comment]
Also, it appears the assembly time is being calculated incorrectly. Currently, it's being set to the sum of the execution times of each collection in the assembly; however, this will be incorrect when running collections in parallel.

I believe this should be set to TestRunCompleteEventArgs.ElapsedTimeInRunningTests, which is "the time elapsed in just running the tests."

https://github.com/Microsoft/vstest/blob/rel/15.9/src/Microsoft.TestPlatform.ObjectModel/Client/Events/TestRunCompleteEventArgs.cs#L73

**Comment by jayeshu** [comment]
Thanks for picking up the task. Will wait for the update.

**Comment by VijayakumarNatarajan** [comment]
Is this issue still open ?

**Comment by jayeshu** [comment]
Yes ... both issues reported above are still open.

**Comment by viktor-kudrya** [comment]
Any updates on this?

**Comment by viktor-kudrya** [comment]
@codito You just need to do the same you did in this commit 
https://github.com/spekt/xunit.testlogger/commit/7dd4e82ff42d962ae66d8d6666e0167912b0d212
but for `CreateTestElement` method as well.

https://github.com/spekt/xunit.testlogger/blob/f1466010a753bf2e975f4ebfddf9a1e105fbe37b/src/Xunit.Xml.TestLogger/XunitXmlTestLogger.cs#L342
"N7" should be changed to "F7"

**Comment by codito** [comment]
Thanks @viktor-kudrya for the investigation. Possible fix is available in build 2.1.40 here: https://www.myget.org/feed/spekt/package/nuget/XunitXml.TestLogger

Please try it out.
