### ISSUE TITLE
Incorrect result for skipped tests?

### ISSUE THREAD

**Issue by Nysosis** [spekt/xunit.testlogger#7]
The [xunit 2 xml spec](https://xunit.github.io/docs/format-xml-v2.html#test) states that a test will be marked as `result='Skip'`, however on [XunitXmlTestLogger.cs#L536](https://github.com/spekt/xunit.testlogger/blob/2c6ef1ac9a70dd67a8dd5dea5cebe63ebc7a6b4a/src/Xunit.Xml.TestLogger/XunitXmlTestLogger.cs#L536) it's emitting the value `Skipped`.

**Comment by Nysosis** [comment]
Just noticed #5 which is fixing this!

**Comment by codito** [comment]
Fixed with 24d031df08d0f73a8ca41a936d267ab6d9306471
